//scriviamo una funzione con un vettore statico per non sprecare memoria con un elenco infinito di informazioni che possono essere prelevate tramite un'indice
//risparmiamo memoria a discapito del rallentamento causto dal dover creare il vettore statico ogni volta che chiamiamo la funzione
//per quanto riguarda i film già scaricati toglierli dall'elenco dei dowload e inserirli nell'elenco di preferenza, mettendo nei link di streaming i percorso assoluto di dove è stato salvato.
const categories = {
    'visto': [1, 5, 13, 46, 55, 79],
    'download': [0, 10, 35, 37, 47, 76, 84],
    'stupendo': [2, 11, 19, 36, 38, 60, 62, 66, 74]
}

function get_films(pos) {
    let list = [
        new Film("10 cose che odio di te!",
            "10 things i hate about you!",
            "https://movieplayer.net-cdn.it/t/images/2003/03/19/la-locandina-di-10-cose-che-odio-di-te-7840_jpg_420x0_crop_q85.jpg",
            "10 cose che odio di te (10 Things I Hate About You) è un film del 1999 diretto da Gil Junger, alla sua prima regia. Il titolo"
            + " della pellicola è ripreso da una poesia recitata nell'opera La bisbetica domata di William Shakespeare, di cui il film è una"
            + " versione cinematografica in chiave giovanile.",
            "", 97, 1999, "", ""),
        new Film("Un uomo tranquillo",
            "Cold Pursuit",
            "https://pad.mymovies.it/filmclub/2018/10/202/locandina.jpg",
            "Un uomo tranquillo (Cold Pursuit) è un film del 2019 diretto da Hans Petter Moland. La pellicola, con protagonista Liam Neeson, "
            + "è il remake del film del 2014 In ordine di sparizione (Kraftidioten), diretto dallo stesso Hans Petter Moland.",
            "", 118, 2019, "", ""),
        new Film("A qualcuno piace caldo",
            "Some Like It Hot",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Some_Like_It_Hot_%281959_poster%29.png/287px-Some_Like_It_Hot_%281959_poster%29.png",
            "A qualcuno piace caldo (Some Like It Hot) è un film del 1959 diretto da Billy Wilder. Considerato uno dei capolavori "
            + "della storia del cinema statunitense[2][3], il film, una divertente e sofisticata commedia della dualità[4], vinse un"
            + " Oscar e tre Golden Globe, tra cui il Golden Globe per la migliore attrice in un film commedia o musicale a Marilyn"
            + " Monroe e miglior attore in un film commedia o musicale a Jack Lemmon, che per la sua interpretazione ricevette anche"
            + " un premio BAFTA. Nel 1989 è stato scelto per la conservazione nel National Film Registry della Biblioteca del Congresso"
            + " degli Stati Uniti d'America[5]. Nel 1998 l'American Film Institute l'ha inserito al quattordicesimo posto della"
            + " classifica dei migliori cento film statunitensi di tutti i tempi[6], mentre dieci anni dopo, nella lista aggiornata,"
            + " è sceso al ventiduesimo posto[7]. Nel 2000 l'ha inserito al primo posto della classifica delle migliori cento commedie "
            + "statunitensi[8]. Nel 2005 la battuta «Well, nobody's perfect» (Beh, nessuno è perfetto) è stata inserita al "
            + "quarantottesimo posto della classifica delle migliori cento battute del cinema statunitense[9].",
            "", 120, 1959, "", ""),
        new Film("Delitti inquietanti",
            "The Glimmer Man",
            "https://pad.mymovies.it/filmclub/2006/04/077/locandina.jpg",
            "Il detective Jack Cole, attivo a New York, viene mandato a Los Angeles per indagare su un pericoloso serial killer che "
            + "è solito crocifiggere le sue vittime dopo averle uccise, fra cui la sua ex moglie.",
            "", 0, 0, "", ""),
        new Film("Giochi di potere",
            "Patriot Games",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("The Time Machine",
            "The Time Machine",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Due facce di un assassino",
            "Face off",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Vanguard",
            "急先鋒",
            "https://upload.wikimedia.org/wikipedia/en/8/84/Vanguard_poster.jpg",
            "",
            "", 0, 0, "", ""),
        new Film("Profumo di donna", //https://it.wikipedia.org/wiki/Scent_of_a_Woman_-_Profumo_di_donna
            "Scent of a Woman",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("6 Underground",
            "6 Underground",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("the tourist",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("starman",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il delinquente del rock and roll",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Blue Hawaii",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Fratelli rivali",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("lo sceriffo scalzo",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("cento ragazze un marinaio",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("zoolander",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("four lions",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("un weekend da bamboccioni",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("fuori in 60 secondi",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("arrivederci professore",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("the majestic",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("amici, amanti e ..",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il principe cerca moglie",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("knowing",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il talento di mr. c",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("i pinguini di mr. popper",
            "",
            "",
            "",
            "", 0, 0, "", "https://www.youtube.com/watch?v=0GAIP6o2s48"),
        new Film("un'impresa da dio",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("birdies",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("tomorrowland",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("strappare lungo i bordi",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("now you see me 1 - i maghi del crimine",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("now you see me 2 - i maghi del crimine",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("now you see me 3 - i maghi del crimine",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("will hunting",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("once upon a time n holliwood",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("yesman",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("la ragazza della porta accanto",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("facciamola finita",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("before sunrise",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("smetto quando voglio 1",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("smetto quando voglio 2",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("smetto quando voglio 3",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("the greatest showman",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il bisbetico domato",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("fidanzata in affitto",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("suxbad",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("una notte da leoni 1",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("una notte da leoni 2",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("una notte da leoni 3",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("notte prima degli esami",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("quei cattivi ragazzi", "good boys", "", "", "", 0, 0, "", ""),
        new Film("la quinta onda",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("in time",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("la ricerca della felicità",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("source code",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("stai scherzando mister fiemann",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il talento di mr ripley",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("50 e 50",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("sliding doors",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("la forza del campione",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("un'impresa da dio",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("don juan de marco - maestro d'amore",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("G.I. joe",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("questione di tempo",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("collateral beauty",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il grande match", "", "", "de niro contro stallone", "", 0, 0, "", ""),
        new Film("mr. deeds",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("luci della ribalta",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("beautifull boys",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("le pagine della nostra vita",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("before we go",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("l'attimo fuggente",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Batman: The killing joke",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("non è mai troppo tardi",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("10 cose che odio di te",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("una tomba per le lucciole",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("scrivimi ancora",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("zodiac",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("exam",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("redlights",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("anatomia di una caduta",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("beatifull mind",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("coach carter",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il sapore della vittoria",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il grande dittatore",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("le ali della libertà",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("ex machina",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("il premio",
            "",
            "",
            "",
            "", 0, 0, "", ""),
        new Film("Profumo di donna",  //https://it.wikipedia.org/wiki/Profumo_di_donna
            "Profumo di donna",
            "",
            "",
            "", 102, 1974, "", "")
    ];
    if (pos === true)
        return list;
    else {
        let returner = [];
        for (let index = 0; index < pos.length; index++) {
            returner.push(list[pos[index]]);
        }
        return returner;
    }
}

function filter_type(type_names) {
    return get_films(categories[type_names]);
}

function offline_research(string, type_names) {
    let search_targets = [];
    let found = [];
    if (type_names.length > 0) {
        for (let index = 0; index < type_names.length; index++) {
            search_targets = search_targets.concat(filter_type(type_names[index]));
        }
    }
    else {
        search_targets = get_films(true);
    }
    console.log("search_targets: ");
    console.log(search_targets);
    if (!string) {
        found = search_targets;
        console.log("stringa di ricerca vuota, found: ");
        console.log(found);
    } else {
        for (let index = 0; index < search_targets.length; index++) {
            let tmp = search_targets[index];
            if (tmp.ti.includes(string))
                found.push(tmp);
            else
                if (tmp.to.includes(string))
                    found.push(tmp);
        }
    }
    console.log("risultati ricerca \'" + string + "\' nelle categorie\'" + type_names + "\': ");
    console.log(found);
    return found;
}

function criterio(list, logic_filter) { //esempio di utilizzo fitraggio per anno:     criterio(found,(film)=>{return film.anno < min || film.anno > max})
    if (logic_filter(/*film in valutazione*/)) { }
}